import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { BsSnapchat } from "react-icons/bs";

export const metadata = {
  title: "Login | Snapchat",
  description: "Generated by create next app",
};

export default function Login() {
  const { data: session } = useSession();
  const router = useRouter();
  const [errorMessage, setErrorMessage] = useState(null);

  useEffect(() => {
    if (session) {
      router.push("/"); // Redirect to home page if logged in
    }
  }, [session,router]); // Run only when session changes

  const handleSignIn = async (provider) => {
    try {
      await signIn(provider);
      setErrorMessage(null); // Clear any previous error message
    } catch (error) {
      console.error("Error signing in:", error);
      setErrorMessage("An error occurred. Please try again."); // Set error message for display
    }
  };

  return (
    <>
    <div className="login-container flex h-[90vh] items-center justify-center bg-yellow-400 flex-col gap-12">
      <span className="text-7xl text-white"><BsSnapchat /></span>
      <div className="login-form bg-white rounded-2xl p-10 flex flex-col items-center gap-4">
        <h1 className="text-2xl font-bold text-gray-800">Welcome to SnapChat</h1>
        <p className="text-gray-600">Please sign in to continue.</p>
        {errorMessage && (
          <div className="text-red-500 font-bold mb-4">{errorMessage}</div>
        )}
        <button
          type="button"
          className="py-2 px-4 rounded-md hover:bg-gray-300 focus:outline-none "
          onClick={() => handleSignIn("github")}
        >
          Sign in with GitHub
        </button>
        <button
          type="button"
          className="py-2 px-4 rounded-md hover:bg-gray-300 focus:outline-none "
          onClick={() => handleSignIn("google")}
        >
          Sign in with Google
        </button>
      </div>
      {errorMessage && <div className="text-red-500 font-bold mb-4">{errorMessage}</div>}
    </div>
    </>
  );
}
